# Setup
title:               Bond's wine
tagline:             'bond'
description:         'A reserved <a href="#" target="_blank">Cindy</a> Made by <a href="#" target="_blank">@blackstrida</a>.'
url:                 https://blackstrida.github.io/bondwine/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              blackstrida
  url:               https://blackstrida.github.io/bondwine/
  email:             blackstrida@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
